### ISSUE TITLE
Provide a callback for link press

### ISSUE THREAD

**Issue by tkodev** [Spoutnik97/react-native-prismic-richtext#5]
Currently links open in another window, but at times rich text might link to another page. If we can expose a `onLinkPress(url, target)` style callback we can intercept the call to open a browser and supply our own behaviour.

What do you think?

**Comment by Spoutnik97** [comment]
Yes, it could be a good improvement. @tkodev  Could you develop this feature, and open a new pull request please? Then I will create a new version
