### ISSUE TITLE
Upgrade to @prismicio/richtext 2.0.1

### ISSUE THREAD

**Issue by bitboxer** [Spoutnik97/react-native-prismic-richtext#9]
We should think of updating to `@prismicio/richtext` and it's companion `@prismicio/types` to get rid of the custom types. That way we can use the official type dictionary and the latest code of the richtext parser.

**Comment by Spoutnik97** [comment]
I agree!

Thanks a lot for your contributions. I don't maintain a lot the package because I don't use it currently. But I keep an eye on it to maintain it thanks to you ;)

**Comment by bitboxer** [comment]
No worries. I am just contributing because I need it in a project. Might be contributing less after the project goes into maintance mode 😉.
